namespace("delian-maze.GameData", {}, () => {

  const floors = {
    "1": "stair-floor",
    "2": "cobblestone",
    "3": "textile-floor",
    "4": "tile-floor",
    "5": "diamond-floor",
    "6": "cave-floor",
    "7": "brick-wall-top",
    "8": "stair-door-bottom"
  }

  const walls = {
    "a": "catacomb-wall-top",
    "b": "catacomb-wall-right",
    "c": "catacomb-wall-bottom",
    "d": "catacomb-wall-left",
    "e": "catacomb-corner-top-left",
    "f": "catacomb-corner-top-right",
    "g": "catacomb-corner-bottom-right",
    "h": "catacomb-corner-bottom-left",
    "i": "cave-wall-left",
    "j": "cave-wall-top",
    "k": "cave-wall-right",
    "l": "cave-wall-bottom",
    "m": "cave-corner-top-left",
    "n": "cave-corner-top-right",
    "o": "cave-corner-bottom-right",
    "p": "cave-corner-bottom-left",
    "q": "brick-wall-top",
    "r": "brick-wall-right",
    "s": "brick-wall-bottom",
    "t": "brick-wall-left",
    "u": "brick-corner-top-left",
    "v": "brick-corner-top-right",
    "w": "brick-corner-bottom-right",
    "x": "brick-corner-bottom-left",
    "y": "brazier-door-top-left",
    "z": "brazier-door-right-top",
    "A": "brazier-door-bottom-right",
    "B": "brazier-door-bottom-left",
    "C": "brazier-door-top-right",
    "D": "brazier-door-right-bottom",
    "E": "brazier-door-left-top",
    "F": "brazier-door-left-bottom",
    "G": "stair-door-top",
    "H": "stair-door-right",
    "I": "stair-door-bottom",
    "J": "stair-door-left",
    "K": "catacomb-edge-top-left",
    "L": "catacomb-edge-top-right",
    "M": "catacomb-edge-bottom-right",
    "N": "catacomb-edge-bottom-left",
  }

  const braziers = {
    "brazier-door-top-left": [0,0,25,50],
    "brazier-door-right-top": [0,0,50,25],
    "brazier-door-bottom-right": [25,0,25,50],
    "brazier-door-bottom-left": [0,0,25,50],
    "brazier-door-top-right": [25,0,25,50],
    "brazier-door-right-bottom": [0,25,50,25],
    "brazier-door-left-top": [0,0,50,25],
    "brazier-door-left-bottom": [0,25,50,25],
  }

  const spriteMap = {
    "a1": "stair-floor",
    "a2": "cobblestone",
    "a3": "textile-floor",
    "a4": "tile-floor",
    "a5": "diamond-floor",
    "a6": "cave-floor",
    "b1": "brazier-door-top-left",
    "b2": "brazier-door-right-top",
    "b3": "brazier-door-bottom-right",
    "b4": "brazier-door-bottom-left",
    "b5": "brazier-door-top-right",
    "b6": "brazier-door-right-bottom",
    "b7": "brazier-door-left-top",
    "b8": "brazier-door-left-bottom",
    "c1": "cave-wall-left",
    "c2": "cave-wall-top",
    "c3": "cave-wall-right",
    "c4": "cave-wall-bottom",
    "c5": "cave-corner-top-left",
    "c6": "cave-corner-top-right",
    "c7": "cave-corner-bottom-right",
    "c8": "cave-corner-bottom-left",
    "d1": "brick-wall-top",
    "d2": "brick-wall-right",
    "d3": "brick-wall-bottom",
    "d4": "brick-wall-left",
    "d5": "brick-corner-top-left",
    "d6": "brick-corner-top-right",
    "d7": "brick-corner-bottom-right",
    "d8": "brick-corner-bottom-left",
    "e1": "catacomb-wall-top",
    "e2": "catacomb-wall-right",
    "e3": "catacomb-wall-bottom",
    "e4": "catacomb-wall-left",
    "e5": "catacomb-corner-top-left",
    "e6": "catacomb-corner-top-right",
    "e7": "catacomb-corner-bottom-right",
    "e8": "catacomb-corner-bottom-left",
    "f1": "catacomb-edge-top-left",
    "f2": "catacomb-edge-top-right",
    "f3": "catacomb-edge-bottom-right",
    "f4": "catacomb-edge-bottom-left",
    "f5": "stair-door-top",
    "f6": "stair-door-right",
    "f7": "stair-door-bottom",
    "f8": "stair-door-left",
    "g1": "acrobat",
    "g2": "cavalier",
    "g3": "presto",
    "g4": "ranger",
    "g5": "thief",
    "g6": "bugbear",
    "g7": "goblin",
    "g8": "nothic",
  };

  const floorMap = [
    "                        ",
    "         6666666666     ",
    "                  8     ",
    "                  7     ",
    "      55666655   223322 ",
    "      33566533   223322 ",
    "      55555555   222222 ",
    "      33555533   222222 ",
    "      55555555   222222 ",
    "      33555533   222222 ",
    "      55533555   222222 ",
    "      55333355   223322 ",
    "                        ",
    "                        ",
    "       222222      55   ",
    "       222222      55   ",
    " 5555  224422  555555   ",
    " 5555  224422  555555   ",
    " 55    222222           ",
    " 55    222222           ",
    "                        ",
  ]

  const wallMap = [
    "        mjjjjjjjjjjn    ",
    "        i          k    ",
    "        pBAlllllll o    ",
    "     eaaayCaaaf uq qqqqv",
    "     d        b t      r",
    "     d        b t      r",
    "     d        b t      r",
    "     d        b t      r",
    "     d        b t      r",
    "     d        b t      r",
    "     d        b t      r",
    "     d        b t      r",
    "     hccccccccg xssBAssw",
    "      uqqqqqqv    eyCf  ",
    "      t      r    d  b  ",
    "eaaaaft      reaaaK  b  ",
    "d    zE      zE      b  ",
    "d    DF      DF      b  ",
    "d  Mcgt      rhccccccg  ",
    "d@ b  t      r          ",
    "hIcg  xssssssw          ",
  ];

  return { spriteMap, floors, walls, floorMap, wallMap, braziers };
});